import { iModalProps } from "@/interfaces/components.interfaces";
import {
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  Heading,
  Input,
  Box,
} from "@chakra-ui/react";

export const ModalMobileFilters = ({ isOpen, onClose }: iModalProps) => {
  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <ModalOverlay />
      <ModalContent borderRadius={"0px"}>
        <ModalHeader>Filtros</ModalHeader>
        <ModalCloseButton color={"grey.4"} />
        <ModalBody>
          <Box flexDirection={"column"} gap={"35px"} display={"flex"}>
            <Box
              gap={"3px"}
              flexDirection={"column"}
              alignItems={"flex-start"}
              display={"flex"}
            >
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Marca
              </Heading>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                General Motors
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Fiat
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Ford
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Honda
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Porshe
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Volswagen
              </Button>
            </Box>
            <Box
              gap={"3px"}
              flexDirection={"column"}
              alignItems={"flex-start"}
              display={"flex"}
            >
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Modelo
              </Heading>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Civic
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Corolla
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Cruze
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Fit
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Gol
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Ka
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Onix
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Porshe 718
              </Button>
            </Box>
            <Box
              gap={"3px"}
              flexDirection={"column"}
              alignItems={"flex-start"}
              display={"flex"}
            >
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Cor
              </Heading>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Azul
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Branco
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Cinza
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Prata
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Preto
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Verde
              </Button>
            </Box>
            <Box
              gap={"3px"}
              flexDirection={"column"}
              alignItems={"flex-start"}
              display={"flex"}
            >
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Ano
              </Heading>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2022
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2021
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2018
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2015
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2013
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2012
              </Button>
              <Button
                fontSize={"20px"}
                display={"box"}
                textAlign={"left"}
                width={"min-content"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                2010
              </Button>
            </Box>
            <Box
              gap={"3px"}
              flexDirection={"column"}
              alignItems={"flex-start"}
              display={"flex"}
            >
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Combustivel
              </Heading>
              <Button
                fontSize={"20px"}
                margin={"0"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Diesel
              </Button>
              <Button
                fontSize={"20px"}
                margin={"0"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Etanol
              </Button>
              <Button
                fontSize={"20px"}
                margin={"0"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Gasolina
              </Button>
              <Button
                fontSize={"20px"}
                margin={"0"}
                padding={"0"}
                height={"min-content"}
                color={"grey.3"}
                variant={""}
              >
                Flex
              </Button>
            </Box>
            <Box>
              <Heading marginBottom={"10px"} fontSize={"28px"}>
                Km
              </Heading>
              <Box gap={"10px"} display={"flex"}>
                <Input
                  borderRadius={"0px"}
                  width={"120px"}
                  padding={"0"}
                  textAlign={"center"}
                  backgroundColor={"grey.5"}
                  type="text"
                  placeholder="Mínima"
                />
                <Input
                  borderRadius={"0px"}
                  width={"120px"}
                  padding={"0"}
                  textAlign={"center"}
                  backgroundColor={"grey.5"}
                  type="text"
                  placeholder="Máxima"
                />
              </Box>
              <Box>
                <Heading marginBottom={"10px"} fontSize={"28px"}>
                  Preço
                </Heading>
                <Box marginBottom={"20px"} gap={"10px"} display={"flex"}>
                  <Input
                    borderRadius={"0px"}
                    width={"120px"}
                    padding={"0"}
                    textAlign={"center"}
                    backgroundColor={"grey.5"}
                    type="text"
                    placeholder="Mínimo"
                  />
                  <Input
                    borderRadius={"0px"}
                    width={"120px"}
                    padding={"0"}
                    textAlign={"center"}
                    backgroundColor={"grey.5"}
                    type="text"
                    placeholder="Máximo"
                  />
                </Box>
              </Box>
            </Box>
            <Button marginBottom={"20px"} variant={"brand1"}>
              Ver anúncios
            </Button>
          </Box>
        </ModalBody>
      </ModalContent>
    </Modal>
  );
};
